### ISSUE TITLE
terminationgraceperiodseconds for jobs

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/harvester_configurations#32]
@fbarreir IIUC the pilot reacts to a SIGTERM signal by starting to clean up and uploading log files, can you confirm if  that is correct?
How long do you estimate it would need to do that?
I can make a PR to set terminationGracePeriodSeconds  to facilitate graceful pod terminations.

**Comment by fbarreir** [comment]
I think I've seen Pilot reacting to SIGTERM in the past, but I don't know the details.  @PalNilsson can better answer this question.

**Comment by PalNilsson** [comment]
Yes, it will take a few minutes typically to tar up the workdir and report to the server. It would be good if you can set the delay to 5 minutes. The pilot will most likely finish well before then.

**Comment by fbarreir** [comment]
I merged your pull request and applied the change.

A general remark: now that your main queue is quite large, IMO you should consider expanding the size and scope of the test queue (e.g. 300 core and set online to run any type of job). You might not see the effect of certain changes on HammerCloud jobs, but it could be a little disaster on the 5k main queue.  (I don't know if this is important for SIGTERM, I'm mostly thinking about memory request&limit proposal)

**Comment by rptaylor** [comment]
I agree, we need several more nodes for the test cluster, maybe not 300 but we can probably do ~ 100 cores at least.
It will require some network changes though.

I would also prefer not to have the affinity and anti-affinity for the pods, or at least keep only one of the two.
